### PR TITLE
Feature/improve markdown git

### PR DESCRIPTION
**Pull request by Charliemowood**
This is to help the team with our pull request abilities.

### CODE REVIEW

**Comment by ChrisPy-RuBy** [comment]
please try harder

**Comment by ChrisPy-RuBy** [comment]
;P

**Comment by Charliemowood** [comment]
Hi Chris,
Thank you so much for catching this.

**Comment by Charliemowood** [comment]
Hi Chris,

I have just made some amendments. I hope it now reaches your high quality standards.

**Pull request merged**
